version: '3'
services:
  nexus-mods-stats:
    build: .
    image: alov/nexus-mods-stats
    restart: always
    depends_on:
      - timescaledb
      # - prometheus
    volumes:
      - ./config.toml:/nm-stats/config.toml
    # for prometheus
    # ports:
    #   - 8000:8000
    command: python ./timescaledb_exporter.py
    # command: python ./prometheus_exporter.py

  timescaledb:
    image: timescale/timescaledb:latest-pg9.6
    restart: always
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      # set this password!!
      POSTGRES_PASSWORD: password

  # prometheus:
  #   image: prom/prometheus:latest
  #   restart: always
  #   expose:
  #     - "9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - ./data/prometheus:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - timescaledb
      # - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
