{
 "title": "ALOV stats for TimescaleDB",
 "tags": [
  "masseffect",
  "nexusmods",
  "alov"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "game", "label": "Game", "query": "SELECT game FROM games;" },
   {
    "name": "modid",
    "label": "Mod",
    "query": "SELECT\n  CONCAT(game,': ',mod) AS __text,\n  CONCAT(mods.gameid,' ',modid) AS __value\nFROM mods\nINNER JOIN games\n  ON mods.gameid = games.gameid\nWHERE game IN ($game);"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "# ALOV download stats\n\nnumbers collected via https://github.com/ALotOfVideos/stats\n\nnote: size calculations are for files downloaded from nexus only, not any mirrors."
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "modid" },
  {
   "type": "aidanmountford-html-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "short",
   "targets": [
    {
     "rawSql": "SELECT\n  picture_url\nFROM games AS g\nINNER JOIN mods AS m\n  ON (g.gameid = m.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) IN ($modid)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  mod\nFROM games AS g\nINNER JOIN mods AS m\n  ON (g.gameid = m.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) IN ($modid)"
    }
   ]
  },
  {
   "type": "aidanmountford-html-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "short",
   "targets": [
    {
     "rawSql": "SELECT\n  game,\n  m.modid\nFROM games AS g\nINNER JOIN mods AS m\n  ON (g.gameid = m.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) IN ($modid)"
    }
   ]
  },
  {
   "title": "Unique Downloads by File",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "alov_masseffect_uniquedownloads",
     "legendFormat": "{{version}} {{name}}",
     "rawSql": "SELECT\n  modversion,\n  filename,\n  MAX(filesizekb) AS filesizekb,\n  MAX(uniquedls) AS uniquedls,\n  MAX(dls) AS dls\nFROM nexus_mod_files_stats AS s\nINNER JOIN nexus_mod_files AS f\n  ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\nINNER JOIN mods AS m ON (s.gameid = m.gameid AND s.modid = m.modid)\nINNER JOIN games AS g ON (s.gameid = g.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) = $modid\nGROUP BY modversion, s.fileid, filename, filesizekb\nORDER BY modversion DESC, filesizekb DESC;"
    }
   ]
  },
  {
   "title": "Unique Download Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"time\",$__interval),\n  CONCAT(modversion, ' ', filename) AS metric,\n  uniquedls - lag(uniquedls) OVER (PARTITION BY s.fileid ORDER BY time) AS delta\nFROM nexus_mod_files_stats AS s\nINNER JOIN nexus_mod_files AS f\n  ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\nINNER JOIN mods AS m\n  ON (s.gameid = m.gameid AND s.modid = m.modid)\nINNER JOIN games AS g\n  ON (s.gameid = g.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) = $modid AND\n  $__timeFilter(\"time\")\nGROUP BY 1,2,uniquedls,s.gameid,s.modid,s.fileid,modversion,s.time\nORDER BY modversion DESC, category ASC, time ASC"
    }
   ]
  },
  {
   "title": "Downloads (Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  CONCAT(modversion, ' ', filename) AS metric,\n  avg(dls) AS \"dls\"\nFROM nexus_mod_files_stats AS s\nINNER JOIN nexus_mod_files AS f\n  ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\nINNER JOIN mods AS m\n  ON (s.gameid = m.gameid AND s.modid = m.modid)\nINNER JOIN games AS g\n  ON (s.gameid = g.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) = $modid AND\n  $__timeFilter(\"time\")\nGROUP BY 1,2,modversion,category\nORDER BY modversion DESC, category ASC, time ASC"
    }
   ]
  },
  {
   "title": "Unique/Downloads by Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (version)(alov_masseffect_uniquedownloads)",
     "legendFormat": "{{version}}",
     "rawSql": "SELECT\r\n  modversion,\r\n  MAX(uniquedls) AS uniquedls,\r\n  MAX(dls) AS dls\r\nFROM (\r\n  SELECT SUM(uniquedls) AS uniquedls, SUM(dls) AS dls, s.gameid, s.modid, modversion\r\n  FROM nexus_mod_files_stats AS s\r\n  INNER JOIN nexus_mod_files AS f\r\n    ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\r\n  GROUP BY s.gameid, s.modid, s.time, modversion\r\n  ) AS s\r\nINNER JOIN mods AS m\r\n  ON (s.gameid = m.gameid AND s.modid = m.modid)\r\nINNER JOIN games AS g\r\n  ON (s.gameid = g.gameid)\r\nWHERE\r\n  CONCAT(m.gameid,' ',m.modid) = $modid\r\nGROUP BY modversion\r\nORDER BY modversion DESC"
    }
   ]
  },
  {
   "title": "Main Files Unique Downloads (Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_uniquedownloads{name!~\".*Unpacker.*\",category=\"MAIN\"}",
     "legendFormat": "{{version}} {{name}}",
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  CONCAT(modversion, ' ', filename) AS metric,\n  avg(uniquedls) AS \"uniquedls\"\nFROM nexus_mod_files_stats AS s\nINNER JOIN nexus_mod_files AS f\n  ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\nINNER JOIN mods AS m\n  ON (s.gameid = m.gameid AND s.modid = m.modid)\nINNER JOIN games AS g\n  ON (s.gameid = g.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) = $modid AND\n  $__timeFilter(\"time\") AND\n  category = 'MAIN'\nGROUP BY 1,2,modversion,category\nORDER BY modversion DESC, category ASC, time ASC"
    }
   ]
  },
  {
   "title": "Other Files Unique Downloads (Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_uniquedownloads{name!~\".*Unpacker.*\",category!=\"MAIN\"}",
     "legendFormat": "{{version}} {{name}}",
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  CONCAT(modversion, ' ', filename) AS metric,\n  avg(uniquedls) AS \"uniquedls\"\nFROM nexus_mod_files_stats AS s\nINNER JOIN nexus_mod_files AS f\n  ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\nINNER JOIN mods AS m\n  ON (s.gameid = m.gameid AND s.modid = m.modid)\nINNER JOIN games AS g\n  ON (s.gameid = g.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) = $modid AND\n  $__timeFilter(\"time\") AND\n  category != 'MAIN'\nGROUP BY 1,2,modversion,category\nORDER BY modversion DESC, category ASC, time ASC"
    }
   ]
  },
  {
   "title": "Size of Unique Downloads (Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_uniquedownloads{name!~\".*Unpacker.*\"}*alov_masseffect_sizes{name!~\".*Unpacker.*\"}",
     "legendFormat": "{{version}} {{name}}",
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  CONCAT(modversion, ' ', filename) AS metric,\n  avg(uniquedls) * filesizekb AS size\nFROM nexus_mod_files_stats AS s\nINNER JOIN nexus_mod_files AS f\n  ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\nINNER JOIN mods AS m\n  ON (s.gameid = m.gameid AND s.modid = m.modid)\nINNER JOIN games AS g\n  ON (s.gameid = g.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) = $modid AND\n  $__timeFilter(\"time\")\nGROUP BY 1,2,modversion,category,filesizekb\nORDER BY size ASC, modversion DESC, category ASC, time ASC"
    }
   ]
  },
  {
   "title": "Unique/Downloads (Total)",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (version)(alov_masseffect_uniquedownloads)",
     "legendFormat": "{{version}}",
     "rawSql": "SELECT\n  MAX(totaldls) AS totaldls,\n  MAX(uniquedls) AS uniquedls,\n  MAX(dls) AS dls\nFROM (\n  SELECT SUM(uniquedls) AS uniquedls, SUM(dls) AS dls, s.gameid, s.modid\n  FROM nexus_mod_files_stats AS s\n  INNER JOIN nexus_mod_files AS f\n    ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\n  GROUP BY s.time, s.gameid, s.modid\n  ) AS s\nINNER JOIN nexus_mod_stats_total AS t\n  ON (s.gameid = t.gameid AND s.modid = t.modid)\nINNER JOIN mods AS m\n  ON (s.gameid = m.gameid AND s.modid = m.modid)\nINNER JOIN games AS g\n  ON (s.gameid = g.gameid)\nWHERE\n  CONCAT(m.gameid,' ',m.modid) = $modid\nGROUP BY s.gameid, s.modid"
    }
   ]
  },
  { "title": "Grand Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Unique Download Activity",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"time\",$__interval),\n  mod as metric,\n  SUM(delta)\nFROM (\n  SELECT\n    time,\n    CONCAT(modversion, ' ', filename) AS modvf,\n    uniquedls - lag(uniquedls) OVER (PARTITION BY s.fileid ORDER BY time) AS delta,\n    mod, game\n  FROM nexus_mod_files_stats AS s\n  INNER JOIN nexus_mod_files AS f\n    ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\n  INNER JOIN mods as m\n    ON (s.gameid = m.gameid AND s.modid = m.modid)\n  INNER JOIN games as g\n    ON (s.gameid = g.gameid)\n  WHERE\n    $__timeFilter(\"time\") AND\n    game IN ('masseffect','masseffect2','masseffect3') AND\n    s.modid IN (144,245,773)\n  GROUP BY 1,2,game,time,s.fileid,uniquedls,mod\n  ) AS d\nGROUP BY mod, time, game\nORDER BY game DESC, time ASC"
    }
   ]
  },
  {
   "title": "Unique Download Activity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"time\",$__interval),\n  mod as metric,\n  SUM(delta)\nFROM (\n  SELECT\n    time,\n    CONCAT(modversion, ' ', filename) AS modvf,\n    uniquedls - lag(uniquedls) OVER (PARTITION BY s.fileid ORDER BY time) AS delta,\n    mod, game\n  FROM nexus_mod_files_stats AS s\n  INNER JOIN nexus_mod_files AS f\n    ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\n  INNER JOIN mods as m\n    ON (s.gameid = m.gameid AND s.modid = m.modid)\n  INNER JOIN games as g\n    ON (s.gameid = g.gameid)\n  WHERE\n    $__timeFilter(\"time\") AND\n    game IN ('masseffect','masseffect2','masseffect3') AND\n    s.modid IN (144,245,773)\n  GROUP BY 1,2,game,time,s.fileid,uniquedls,mod\n  ) AS d\nGROUP BY mod, time, game\nORDER BY game ASC, time ASC"
    }
   ]
  },
  {
   "title": "Total Unique Downloads",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(alov_masseffect_uniquedownloads)",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\r\n  mod,\r\n  MAX(totaldls) AS totaldls,\r\n  SUM(f.uniquedls) AS uniquedls,\r\n  SUM(f.usize) AS usize,\r\n  SUM(f.dls) AS dls,\r\n  SUM(f.size) AS size\r\nFROM (\r\n  SELECT\r\n    game,\r\n    s.gameid,\r\n    s.modid,\r\n    MAX(s.uniquedls) AS uniquedls,\r\n    MAX(s.dls) AS dls,\r\n    MAX(s.uniquedls)::bigint * MAX(filesizekb) AS usize,\r\n    MAX(s.dls)::bigint * MAX(filesizekb) AS size,\r\n    s.fileid\r\n  FROM nexus_mod_files_stats AS s\r\n  INNER JOIN nexus_mod_files AS f\r\n    ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\r\n  INNER JOIN games AS g\r\n    ON (s.gameid = g.gameid)\r\n  WHERE\r\n    game IN ($game) AND\r\n    s.modid IN (144,245,773)\r\n  GROUP BY 1,2,3,s.fileid\r\n            ) AS f\r\nINNER JOIN mods AS m\r\n  ON (f.gameid = m.gameid and f.modid = m.modid)\r\nINNER JOIN nexus_mod_stats_total AS t\r\n  ON (f.gameid = t.gameid AND f.modid = t.modid)\r\nWHERE\r\n  game IN ($game) AND\r\n  f.modid IN (144,245,773)\r\nGROUP BY f.modid,f.gameid,mod,game\r\nORDER BY game"
    },
    {
     "expr": "sum(alov_masseffect_uniquedownloads)",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\r\n  'Total' AS mod,\r\n  SUM(totaldls) AS totaldls,\r\n  SUM(uniquedls) AS uniquedls,\r\n  SUM(usize) AS usize,\r\n  SUM(dls) AS dls,\r\n  SUM(size) AS size\r\nFROM (\r\n  SELECT\r\n    mod,\r\n    MAX(totaldls) AS totaldls,\r\n    SUM(f.uniquedls) AS uniquedls,\r\n    SUM(f.usize) AS usize,\r\n    SUM(f.dls) AS dls,\r\n    SUM(f.size) AS size\r\n  FROM (\r\n    SELECT\r\n      game,\r\n      s.gameid,\r\n      s.modid,\r\n      MAX(s.uniquedls) AS uniquedls,\r\n      MAX(s.dls) AS dls,\r\n      MAX(s.uniquedls)::bigint * MAX(filesizekb) AS usize,\r\n      MAX(s.dls)::bigint * MAX(filesizekb) AS size\r\n    FROM nexus_mod_files_stats AS s\r\n    INNER JOIN nexus_mod_files AS f\r\n      ON (s.gameid = f.gameid AND s.modid = f.modid AND s.fileid = f.fileid)\r\n    INNER JOIN games AS g\r\n      ON (s.gameid = g.gameid)\r\n    WHERE\r\n      game IN ($game) AND\r\n      s.modid IN (144,245,773)\r\n    GROUP BY 1,2,3,s.fileid\r\n              ) AS f\r\n  INNER JOIN mods AS m\r\n    ON (f.gameid = m.gameid and f.modid = m.modid)\r\n  INNER JOIN nexus_mod_stats_total AS t\r\n    ON (f.gameid = t.gameid AND f.modid = t.modid)\r\n  WHERE\r\n    game IN ($game) AND\r\n    f.modid IN (144,245,773)\r\n  GROUP BY f.modid,f.gameid,mod,game\r\n  ORDER BY game\r\n  ) AS t"
    }
   ]
  },
  {
   "title": "Daily Downloads (Nexus)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_endorsements",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\n  $__timeGroup(\"time\",$__interval),\n  mod AS metric,\n  dailydls\nFROM nexus_mod_stats_daily AS d\nINNER JOIN mods AS m\n  ON (d.gameid = m.gameid AND d.modid = m.modid)\nINNER JOIN games AS g\n  ON (d.gameid = g.gameid)\nWHERE\n  $__timeFilter(\"time\") AND\n  game IN ('masseffect','masseffect2','masseffect3') AND\n  d.modid IN (144,245,773)\nORDER BY game, time ASC"
    }
   ]
  },
  {
   "title": "Daily Page Views",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_endorsements",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\n  $__timeGroup(\"time\",$__interval),\n  mod AS metric,\n  pageviews\nFROM nexus_mod_stats_daily AS d\nINNER JOIN mods AS m\n  ON (d.gameid = m.gameid AND d.modid = m.modid)\nINNER JOIN games AS g\n  ON (d.gameid = g.gameid)\nWHERE\n  $__timeFilter(\"time\") AND\n  game IN ('masseffect','masseffect2','masseffect3') AND\n  d.modid IN (144,245,773)\nORDER BY game, time ASC"
    }
   ]
  },
  {
   "title": "Endorsements",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "alov_masseffect_endorsements",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\n  mod AS metric,\n  MAX(endorsements) AS endorsements,\n  pageviews AS pageviews\nFROM endorsements AS e\nINNER JOIN (\n  SELECT\n    gameid, modid,\n    SUM(pageviews) AS pageviews\n  FROM nexus_mod_stats_daily\n  GROUP BY 1,2\n  ) AS p\n  ON (e.gameid = p.gameid AND e.modid = p.modid)\nINNER JOIN mods AS m\n  ON (e.gameid = m.gameid and e.modid = m.modid)\nINNER JOIN games AS g\n  ON (e.gameid = g.gameid)\nWHERE\n  game IN ('masseffect','masseffect2','masseffect3') AND\n  e.modid IN (144,245,773)\nGROUP BY 1,3\nORDER BY mod ASC"
    },
    {
     "expr": "alov_masseffect_endorsements",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\r\n  'Total' AS metric,\r\n  SUM(e.endorsements) AS endorsements,\r\n  SUM(e.pageviews) AS pageviews\r\nFROM (\r\n  SELECT\r\n    mod AS metric,\r\n    MAX(endorsements) AS endorsements,\r\n    pageviews AS pageviews\r\n  FROM endorsements AS e\r\n  INNER JOIN (\r\n    SELECT\r\n      gameid, modid,\r\n      SUM(pageviews) AS pageviews\r\n    FROM nexus_mod_stats_daily\r\n    GROUP BY 1,2\r\n    ) AS p\r\n    ON (e.gameid = p.gameid AND e.modid = p.modid)\r\n  INNER JOIN mods AS m\r\n    ON (e.gameid = m.gameid and e.modid = m.modid)\r\n  INNER JOIN games AS g\r\n    ON (e.gameid = g.gameid)\r\n  WHERE\r\n    game IN ('masseffect','masseffect2','masseffect3') AND\r\n    e.modid IN (144,245,773)\r\n  GROUP BY 1,3\r\n  ORDER BY mod ASC\r\n  ) AS e"
    }
   ]
  },
  {
   "title": "Endorsements",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_endorsements",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\n  $__timeGroup(\"time\",$__interval),\n  mod AS metric,\n  endorsements\nFROM endorsements AS e\nINNER JOIN mods AS m\n  ON (e.gameid = m.gameid AND e.modid = m.modid)\nINNER JOIN games AS g\n  ON (e.gameid = g.gameid)\nWHERE\n  $__timeFilter(\"time\") AND\n  game IN ('masseffect','masseffect2','masseffect3') AND\n  e.modid IN (144,245,773)\nORDER BY game, time ASC"
    }
   ]
  },
  {
   "title": "Daily Endorsements",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_endorsements",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\n  time,\n  mod AS metric,\n  endorsements - lag(endorsements) OVER (PARTITION BY m.modid) AS delta\nFROM (\n  SELECT\n    $__timeGroupAlias(time,$__interval),\n    gameid,\n    modid,\n    SUM(endorsements) AS endorsements\n  FROM endorsements\n  GROUP BY 1,2,3\n  ORDER BY time,gameid,modid\n  ) AS e\nINNER JOIN mods AS m\n  ON (e.gameid = m.gameid AND e.modid = m.modid)\nINNER JOIN games AS g\n  ON (e.gameid = g.gameid)\nWHERE\n  $__timeFilter(e.time) AND\n  game IN ('masseffect','masseffect2','masseffect3') AND\n  e.modid IN (144,245,773)\nGROUP BY 1,2,game,m.modid,endorsements\nORDER BY game, time ASC"
    }
   ]
  },
  {
   "title": "Daily Downloads per Views",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_endorsements",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\r\n  $__timeGroup(\"time\",$__interval),\r\n  mod AS metric,\r\n  (CAST(dailydls AS FLOAT) / CAST(pageviews AS FLOAT)) AS rate\r\nFROM nexus_mod_stats_daily AS d\r\nINNER JOIN mods AS m\r\n  ON (d.gameid = m.gameid AND d.modid = m.modid)\r\nINNER JOIN games AS g\r\n  ON (d.gameid = g.gameid)\r\nWHERE\r\n  $__timeFilter(\"time\") AND\r\n  game IN ('masseffect','masseffect2','masseffect3') AND\r\n  d.modid IN (144,245,773)\r\nORDER BY game, time ASC"
    }
   ]
  },
  {
   "title": "Daily Downloads per Views compared to Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "alov_masseffect_endorsements",
     "legendFormat": "ALOV for ME1",
     "rawSql": "SELECT\r\n  $__timeGroup(\"time\",$__interval),\r\n  mod AS metric,\r\n  (rate/total) - 1 AS rrate\r\nFROM (\r\n  SELECT\r\n    d.gameid,\r\n    d.modid,\r\n    d.time,\r\n    (CAST(dailydls AS FLOAT) / CAST(pageviews AS FLOAT)) AS rate\r\n  FROM nexus_mod_stats_daily AS d\r\n  ) AS d\r\nINNER JOIN (\r\n  SELECT\r\n    d.gameid,\r\n    d.modid,\r\n    game,\r\n    CAST(SUM(dailydls) AS FLOAT) / CAST(SUM(pageviews) AS FLOAT) AS total\r\n  FROM nexus_mod_stats_daily AS d\r\n  INNER JOIN games AS g\r\n    ON (d.gameid = g.gameid)\r\n  WHERE\r\n    game IN ('masseffect','masseffect2','masseffect3') AND\r\n    d.modid IN (144,245,773)\r\n  GROUP BY d.gameid,modid,game\r\n  ) AS t\r\n  ON (d.gameid = t.gameid AND d.modid = t.modid)\r\nINNER JOIN mods AS m\r\n  ON (d.gameid = m.gameid AND d.modid = m.modid)\r\nWHERE\r\n  $__timeFilter(\"time\") AND\r\n  game IN ('masseffect','masseffect2','masseffect3') AND\r\n  d.modid IN (144,245,773)\r\nORDER BY game, time ASC"
    }
   ]
  }
 ]
}